name: Continuous Deployment VM

on:
  push:
    branches:
      - Deployment

jobs:
  deploy:
    runs-on: self-hosted  # O job será executado no runner self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into the VM and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSW }}
          script: |
            echo "Deploying to VM..."
            cd ~/actions-runner/_work/ies-24-25-group-project-403/ies-24-25-group-project-403

            docker compose down --remove-orphans
            docker compose up --build -d
