FROM python:3.9-slim
WORKDIR /app
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY producer.py .
COPY kafka_wait.sh .
RUN chmod +x kafka_wait.sh
CMD ["./kafka_wait.sh", "kafka:9092", "python", "producer.py"]